Reg       = "What have the Romans ever given us?"
man1      = "The aqueduct?"
2ndMan    = "The sanitation"
m@n3      = "And the roads"
man_4     = "Irrigation"
man 5     = "Medicine"
SixthMan  = "Education"
man_no._7 = "And the wine!"
8thMan    = "Public votes"
no9atReg  = "Public order; it's finally safe to walk"
            "in the streets at night."
reg       = "All right. But apart from sanitation,"
            "medicine, education, wine, public order,"
            "irrigation, roads, a fresh water system,"
            "and public health;"
            "what have the Romans ever done for us?"